# Configurații pentru build-ul pe Netlify
[build]
  # Directorul unde se află funcțiile serverless
  functions = "netlify/functions"
  # Directorul cu fișiere statice (ex: index.html, css) de publicat
  publish = "public"

# Redirecționăm toate cererile către /api/* și /graphiql către funcția noastră
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/graphiql"
  to = "/.netlify/functions/api/graphiql"
  status = 200